### ISSUE TITLE
Wrong usage of HueBridge constructor: IP and name are reversed

### ISSUE THREAD

**Issue by seveno-marc** [ZeroOne3010/yetanotherhueapi#15]
https://github.com/ZeroOne3010/yetanotherhueapi/blob/d846ad0e3bd6e3ebe2e32594d780855e9a589633/src/main/java/io/github/zeroone3010/yahueapi/discovery/HueBridgeDiscoveryService.java#L98

Name and IP are reversed on HueBridge object recieved through discovery service.

**Comment by ZeroOne3010** [comment]
Wow, that's a bummer... Thanks for reporting!

**Comment by ZeroOne3010** [comment]
The fix has now been released in version 1.3.1. Thank you and sorry, @seveno-marc! (It seems that you created a GitHub account just to report this issue, I'm humbled! :bowing_man:)
