### ISSUE TITLE
UPnPDiscoverer V1 Bridge is not working

### ISSUE THREAD

**Issue by jeroenbeuz** [ZeroOne3010/yetanotherhueapi#29]
Hey I kinda used your  UPnPDiscoverer as an example to get it working in my app. Had to rewrite it to Kotlin. It all worked but since a couple of days I can't seem to find V1 Bridges. Is that still working for you?

Thanks

**Comment by ZeroOne3010** [comment]
Hey, nice to hear my library was of some help for you this way! Unfortunately I myself have no experience with the V1 bridge whatsoever. The UPnPDiscoverer still does seem to work with my V2 bridge, though.

You might be interested to hear that a Kotlin conversion was actually discussed already in #11 where this guy @TobseF did one. He mentioned that it's the dependency to the java.awt.Color class that prevents this library from being used in Android projects. Now, finally, I'm in the process of removing that dependency in #25!
