### ISSUE TITLE
getScene returns null

### ISSUE THREAD

**Issue by jonteohr** [ZeroOne3010/yetanotherhueapi#35]
I'm trying to get the current scene of a room before changing it, but since I can't do that (from what I've found) I'm trying to get the scene of the two lights in that room like this:
```
prevScene = room.getLightByName("left light").get().getState().getScene();
```

However that just returns `null`. Am I using it wrong or is this a bug?

**Comment by ZeroOne3010** [comment]
Hey, thanks for submitting an issue! Unfortunately that's not how scenes work. You recall one, it adjusts the affected lights -- and afterwards there's no way to know how the lights got to their current state. Even if it worked like you thought, relying on scenes still wouldn't be a good idea: what would the API even say as the scene of a room or a light, when a scene has been recalled, but some lights then adjusted manually?

I do sympathize with your confusion, the library kind of does lead you to believe it would work like that. 😞 Actually the getter method is there so you can read the settings you put into a scene yourself, when you are about to activate a scene. So the `State` object is kind of different depending on whether you created it or whether you got it from a `Light` or a `Room`, as the API does not populate all those values that you yourself can use.

All this being said, the solution to your problem should be to simply get the _states_ of the lights in the room, not the scenes. 😃 Remember to enable caching (`Hue#setCaching(true)`) before you get the states of all the lights. That way it does not call the API ten times if there are ten lights in the room. Then, once you've stored the states, disable caching again. There's more on the subject of caching in [README.md](https://github.com/ZeroOne3010/yetanotherhueapi/blob/master/README.md).

I will add Javadoc comments for the `State#getScene()` method clarifying the issue! Thank you and sorry again. 😅

**Comment by jonteohr** [comment]
Thank you very much for that explanation! Will continue to test and see how I'll solve this :)
