### ISSUE TITLE
Turn on / off room without setState (color, alert, etc...)

### ISSUE THREAD

**Issue by vippergod123** [ZeroOne3010/yetanotherhueapi#44]
Hi, dev teams

I'm using your great library to control Philips hue lights. But I got 1 issue that when I want to turn off/on lights in room, I just want toggle lights (keep current lights state in the room) but I can't find any function to do that.

Could you provide users a function just only toggle room light? or maybe I miss it?

Thank you for your library.

**Comment by ZeroOne3010** [comment]
Hi there, and thanks for your message! You're right, it seems that the library is indeed missing a feature to turn on/off all the lights in a room at once without touching the other state variables! That's a silly omission, considering that the `Light` interface does already have `turnOn()` and `turnOff()` methods.

Until I get to adding this feature, you can see how the `LightImpl` class actually implements those on and off methods and adapt it to rooms like this:

`````
room.setState(((StateBuilderSteps.OnOffStep) State.builder()).on())
`````

Hope this helps! 😃

**Comment by ZeroOne3010** [comment]
Hi again! This has now been remedied in version `2.3.0`: the `Room `objects now have the same `turnOn()` and `turnOff()` methods as the `Light `objects. Cheers!
