### ISSUE TITLE
Server-Sent Events

### ISSUE THREAD

**Issue by philipparndt** [ZeroOne3010/yetanotherhueapi#48]
The Hue API v2 (currently in beta) added support for push notifications using SSE.

This would be a great enhancement when working with buttons. 

Do you have a plan to support this?

**Comment by ZeroOne3010** [comment]
Hey, thanks for submitting this as an issue! You are definitely right, the SSE would be an awesome feature to have and I'll definitely want the library to have it some day! 🤩 Unfortunately I haven't had much time to work on this library lately, but I'm hoping I'll get a bit more time starting next week. For now, what little time I've had, I've spent on #46 to add mDNS discovery support, as Philips is deprecating the UPNP discovery method.

While I'm hoping the SSE feature in itself might be a pretty straight forward one to implement, it would need more of the new v2 API to be implemented around it. For one, the SSE API identifies the devices with a UUID, which does not exist in the API v1. Also, when implementing the API v2, I would need to see if it can be compatible with the current interfaces that the library offers, or if I should just be bold and break all the backwards compatibility and release new major version (3.0.0) that would support the API v2 only.

For now I'm hoping I could add SSE into the current version without breaking backwards compatibility, but to fully support everything else that the new API v2 offers a new major version might be required. I would still need to explore and experiment with the new API to form a full picture of the situation.

Finally, I'm slightly worried about the beta status of the server-sent events, as that would mean the API might still change, which would not be good for the library. Maybe a beta version of the library is needed while the API is in beta, too. 🤔 So, a lot to consider here!

As a note to mainly myself, the docs for the server-sent events can be found here: https://developers.meethue.com/develop/hue-api-v2/core-concepts/#events

**Comment by philipparndt** [comment]
Hi,

I started to do some tests with the SSE API. It is pretty easy to use, but the identifiers are no longer compatible, as you already mentioned. I also found another incompatible change for the Friends Of Hue buttons. There is no push notification when pressing two buttons at once. The old API reported this as an extra button, which was nice.

I've used this dependency in my tests https://github.com/autopreet/apache-sseclient, but the byte-code is not compatible with Java 8.

**Comment by ZeroOne3010** [comment]
Luckily the client side of the SSE protocol seems simple enough, there should be no need to use any libraries... 🤞

**Comment by NathanSweet** [comment]
Getting events from the server rather than polling is crucial. I'd suggest making breaking changes to support v2. People who want to continue using v1 can use the older version of this library.

**Comment by ZeroOne3010** [comment]
Just to close this old issue: version `3.0.0-alpha` is now out and it supports those server sent events. :heart:
