### ISSUE TITLE
Implement a findByUiniqueId for lights and sensors

### ISSUE THREAD

**Issue by koenraadvds** [ZeroOne3010/yetanotherhueapi#49]
I would like to contribute a patch that allows the use of the uniqueId to search for lights and presence sensor. However, the new github authentication don't allow me to push the changes. Is there any group or email where i can post the patch?

**Comment by ZeroOne3010** [comment]
Hey, cool! Patches would definitely be welcome. :) Am I guessing right that this is about the new API v2, as the library does not have any support for it yet? I pondered about the implications of changing into API v2 in issue #48, it's not entirely straight forward, but I could probably accept your patch into some branch at least.

I do recommend that you would still try pushing your changes and creating a pull request the normal way. You cannot use your password with the command line anymore, you just need a personal access token as described here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#authenticating-with-the-command-line -- and obviously you cannot push directly into my repository, you need to fork this project to your account first, push the changes there, and then create a pull request from there.

Everything else failing I suppose you could copy & paste your patch to this issue and I could see what I could do with it.

**Comment by koenraadvds** [comment]
From 1a67e8f118c25858debc098009eeaa501e13ee06 Mon Sep 17 00:00:00 2001
From: koenraadvds <k.vanderschaeve@gmail.com>
Date: Thu, 27 Jan 2022 12:17:04 +0100
Subject: [PATCH] add uniqueid to lights and sensors

---
 .../java/io/github/zeroone3010/yahueapi/BasicSensor.java  | 7 +++++++
 src/main/java/io/github/zeroone3010/yahueapi/Light.java   | 6 ++++++
 .../java/io/github/zeroone3010/yahueapi/LightImpl.java    | 8 ++++++++
 src/main/java/io/github/zeroone3010/yahueapi/Sensor.java  | 6 ++++++
 4 files changed, 27 insertions(+)

diff --git a/src/main/java/io/github/zeroone3010/yahueapi/BasicSensor.java b/src/main/java/io/github/zeroone3010/yahueapi/BasicSensor.java
index 2a4dcaf..30db84e 100644
--- a/src/main/java/io/github/zeroone3010/yahueapi/BasicSensor.java
+++ b/src/main/java/io/github/zeroone3010/yahueapi/BasicSensor.java
@@ -15,6 +15,7 @@ class BasicSensor implements Sensor {
 
   protected final String id;
   protected final String name;
+  protected final String uniqueid;
   protected final String productName;
   protected final URL baseUrl;
   protected final SensorType type;
@@ -26,6 +27,7 @@ class BasicSensor implements Sensor {
       throw new HueApiException("Sensor " + id + " cannot be found.");
     }
     this.name = sensor.getName();
+    this.uniqueid = sensor.getUniqueId();
     this.productName = sensor.getProductName();
     this.baseUrl = url;
     this.stateProvider = stateProvider;
@@ -75,4 +77,9 @@ class BasicSensor implements Sensor {
         ", type=" + type +
         '}';
   }
+
+	@Override
+	public String getUniqueid() {
+		return this.uniqueid;
+	}
 }
diff --git a/src/main/java/io/github/zeroone3010/yahueapi/Light.java b/src/main/java/io/github/zeroone3010/yahueapi/Light.java
index 10e17ce..34b5539 100644
--- a/src/main/java/io/github/zeroone3010/yahueapi/Light.java
+++ b/src/main/java/io/github/zeroone3010/yahueapi/Light.java
@@ -87,4 +87,10 @@ public interface Light {
    * @since 2.4.0
    */
   Integer getMaxLumens();
+  
+  /**
+   * Returns the unique identifier for the light
+   * @return
+   */
+  String getUniqueid();
 }
diff --git a/src/main/java/io/github/zeroone3010/yahueapi/LightImpl.java b/src/main/java/io/github/zeroone3010/yahueapi/LightImpl.java
index d4db2f4..6f76824 100644
--- a/src/main/java/io/github/zeroone3010/yahueapi/LightImpl.java
+++ b/src/main/java/io/github/zeroone3010/yahueapi/LightImpl.java
@@ -12,6 +12,7 @@ final class LightImpl implements Light {
 
   private final String id;
   private final String name;
+  private final String uniqueid;
   private final Supplier<LightState> stateProvider;
   private final Function<State, String> stateSetter;
   private final LightType type;
@@ -24,6 +25,7 @@ final class LightImpl implements Light {
       throw new HueApiException("Light " + id + " cannot be found.");
     }
     this.name = light.getName();
+    this.uniqueid = light.getUniqueid();
     this.stateProvider = stateProvider;
     this.stateSetter = stateSetter;
     this.type = LightType.parseTypeString(light.getType());
@@ -101,4 +103,10 @@ final class LightImpl implements Light {
         ", maxLumens=" + maxLumens +
         '}';
   }
+
+  @Override
+  public String getUniqueid() {
+  	return this.uniqueid;
+  }
+  
 }
diff --git a/src/main/java/io/github/zeroone3010/yahueapi/Sensor.java b/src/main/java/io/github/zeroone3010/yahueapi/Sensor.java
index 646bdd6..29914fd 100644
--- a/src/main/java/io/github/zeroone3010/yahueapi/Sensor.java
+++ b/src/main/java/io/github/zeroone3010/yahueapi/Sensor.java
@@ -41,4 +41,10 @@ public interface Sensor {
    * @return The time when the sensor status was last updated, or null.
    */
   ZonedDateTime getLastUpdated();
+  
+  /**
+   * Returns the uniqueid for the sensor.
+   * @return
+   */
+  String getUniqueid();
 }
-- 
2.24.3 (Apple Git-128)

From 3991a2893214f94ccfd6f286d9c06113704cf21a Mon Sep 17 00:00:00 2001
From: koenraadvds <k.vanderschaeve@gmail.com>
Date: Wed, 2 Feb 2022 12:01:03 +0100
Subject: [PATCH] findByUniqueId for lights and prescense sensor

---
 .../java/io/github/zeroone3010/yahueapi/Hue.java  | 15 +++++++++++++++
 .../java/io/github/zeroone3010/yahueapi/Room.java |  8 ++++++++
 .../io/github/zeroone3010/yahueapi/RoomImpl.java  |  7 +++++++
 3 files changed, 30 insertions(+)

diff --git a/src/main/java/io/github/zeroone3010/yahueapi/Hue.java b/src/main/java/io/github/zeroone3010/yahueapi/Hue.java
index 97a6de6..48cb59c 100644
--- a/src/main/java/io/github/zeroone3010/yahueapi/Hue.java
+++ b/src/main/java/io/github/zeroone3010/yahueapi/Hue.java
@@ -372,6 +372,21 @@ public final class Hue {
         .findFirst();
   }
 
+  /**
+   * Returns a specific presence sensor by its uniqueId.
+   *
+   * @param uniqueId The uniqueId of the sensor
+   * @return A sensor or {@code Optional.empty()} if a sensor with the given uniqueId does not exist.
+   * @since 2.0.0
+   */
+  public Optional<PresenceSensor> getPresenceSensorByUniqueId(final String uniqueId) {
+    doInitialDataLoadIfRequired();
+    return getPresenceSensors().stream()
+        .filter(sensor -> Objects.equals(sensor.getUniqueid(), uniqueId))
+        .map(PresenceSensor.class::cast)
+        .findFirst();
+  }
+  
   /**
    * Returns a specific ambient sensor by its name.
    *
diff --git a/src/main/java/io/github/zeroone3010/yahueapi/Room.java b/src/main/java/io/github/zeroone3010/yahueapi/Room.java
index bbd6404..0eb3f94 100644
--- a/src/main/java/io/github/zeroone3010/yahueapi/Room.java
+++ b/src/main/java/io/github/zeroone3010/yahueapi/Room.java
@@ -41,6 +41,14 @@ public interface Room {
    */
   Optional<Light> getLightByName(String lightName);
 
+  /**
+   * Returns one light, if found by the given unique id.
+   *
+   * @param uniqueId uniqueId of a light in this group.
+   * @return Optional.empty() if a light is not found by this uniqueId, an Optional&lt;Light&gt; if it is.
+   */
+  Optional<Light> getLightByUniqueId(String uniqueId);
+  
   /**
    * Queries the state of the group of lights.
    *
diff --git a/src/main/java/io/github/zeroone3010/yahueapi/RoomImpl.java b/src/main/java/io/github/zeroone3010/yahueapi/RoomImpl.java
index 1d67291..b997816 100644
--- a/src/main/java/io/github/zeroone3010/yahueapi/RoomImpl.java
+++ b/src/main/java/io/github/zeroone3010/yahueapi/RoomImpl.java
@@ -60,6 +60,13 @@ final class RoomImpl implements Room {
         .findFirst();
   }
 
+  @Override
+  public Optional<Light> getLightByUniqueId(final String uniqueId) {
+    return lights.stream()
+        .filter(light -> Objects.equals(light.getUniqueid(), uniqueId))
+        .findFirst();
+  }
+  
   @Override
   public boolean isAnyOn() {
     return getGroupState().isAnyOn();
-- 
2.24.3 (Apple Git-128)

**Comment by koenraadvds** [comment]
Hi,

Well, no, not API v2. It’s a patch to your “yetanotherhueapi” V3.2 i’m currently using. The problem is that when i refer to a light or sensor by name, that name could change and than breaks the reference. I saw that there is also a uniqueId available. S i extended the lib to use the uniqueId to find lights and sensors.

Attached is the patch.

Regards,

Koenraad

**Comment by ZeroOne3010** [comment]
Oh, I see now! When you wrote about "unique id" that immediately got me thinking about the new API version that the Bridge exposes, the API v2, that this library does not support yet. See, in that new API the ids that the various entities have are universally unique, also known as UUIDs, such as "4cf84bbc-312e-4be9-bf6c-601edc6aab46". But yes, you are referring to the ids that the good old API v1 is using, such as "1", "2", etc.

I believe that you must be using version 2.3.0 of the library then, not 3.2. Now, you're in luck, because in version 2.4.0 the ids for both lights and rooms are indeed exposed! :) This was implemented in the context of issue #45. Sensors ids aren't exposed yet, but that can definitely be added. :+1:

**Comment by koenraadvds** [comment]
Hi,

Actually, i am not referring to the “id” but to the “uniqueId" in the API v1 json (e.g. "uniqueid": "00:17:88:01:03:b5:34:24-0b”) But on the other hand, in API v2, the uniqueId is replaced by uuid as you already mentioned. And further reading about API v2 also reveals than the “id” might also retire. It will be in for some time to allow libraries to migrate between v1 and v2 smoothly. Finally, the uuid in v2 will be the preferred method to identify the devices.

Interesting however in the api v2 is the SSE implementation to avoid polling devices. I try to test this functionality using a SSE client from jax-rs but without success for the moment :(

Kind regards,

Koenraad Vanderschaeve

**Comment by ZeroOne3010** [comment]
Hello! Yes, sorry, I _finally_ understand what you mean: there is indeed a `uniqueId` attribute for the lights in API v1! Apparently there always has been, but I've never really paid any attention to it. :o I am inclined to think that it would actually be a disservice for anyone using this library to introduce it now, with API v2 practically just around the corner... There wouldn't really be much time to enjoy it for I do want to convert the library into using API v2 sooner or later.

**Comment by koenraadvds** [comment]
Hi,

I understand that it is more interesting to convert the library to v2. By this time i tested the SSE implementation in the v2 API. It works very well and will be a big advantage over polling for the state of devices.

Kind regards,

Koenraad

**Comment by koenraadvds** [comment]
Hi,

Did you had the chance to validate the simple patch i’ve send you last week to exposure the uniqueId of sensor and lights to add to your lib? I attached another simple patch in this mail that expose the id of a scene. A scene can only be found by name now. If the name changes, the scene cannot be found anymore. Therefor the id should be better.
Anyhow, i have build my own version of your lib with those changes in order to use them in my project. 

Kind regards,

Koenraad

**Comment by ZeroOne3010** [comment]
Hi there! Unfortunately no, I must admit I haven't tried the patches... I think the regular ids should be exposed first, not necessarily the unique ids, for that's what has been done with the lights and rooms. Also, I don't know how many versions of this library I will publish before moving on to API v2, at which point the interfaces will need to be changed anyway. I will keep this issue open so that if I can come up with some other feature(s) besides these id accessors, I will remember to add these too into a new version. And hey, it's good that you managed to build your own version! Power of open source software, huh? :)

**Comment by ZeroOne3010** [comment]
@koenraadvds Hi, I've just released a new version of the library, 2.7.0, where you have a new `getId()` method for Scenes too. Now scenes, rooms, lights and sensors have one. It's still not the unique id you asked for, but it's an id for all of them anyway.

You might also be interested in the `api-v2` branch that I've been working on: it is very rudimentary, but you can now use it to toggle lights on and off with the new API. 😅 There, anyway, each resource will have a long UUID.

**Comment by koenraadvds** [comment]
Hi,

Thx! I’ll check it out!

Regards,

Koenraad

**Comment by ZeroOne3010** [comment]
Version `3.0.0-alpha` is now out, and there all the entities are referred to by their `UUID`. :heart: I'm just going to go ahead and close this issue, but feel free to still comment here to let me know how that works for you! I'm also looking for any and all feedback on the latest version so that I could eventually promote it to `3.0.0`, so opening new issues would be much appreciated too. :pray: Cheers!
