### ISSUE TITLE
thank you so much

### ISSUE THREAD

**Issue by MrBlik123** [ZeroOne3010/yetanotherhueapi#5]
i really dont have any issues exept importing the pacakge but thats probaply just me since i just learned java but i just wanna say thank you for making this and putting so much effort in

**Comment by ZeroOne3010** [comment]
Cool, thank you for your kind words! I'm happy to know someone else finds this library useful, too! :smiley: "Importing the package" is indeed pretty much how Java works, so unfortunately there's no way around it. :stuck_out_tongue_winking_eye:
