### ISSUE TITLE
hue cannot be resolved to a type

### ISSUE THREAD

**Issue by MrBlik123** [ZeroOne3010/yetanotherhueapi#6]
i am still a beginner programmer so this issue could be related to me but im getting this problem when im trying to ouput on or off

Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	Hue cannot be resolved
	Hue cannot be resolved to a type
	Hue cannot be resolved to a type

^^ is the error that im getting

this is my code
package Philips_hue;

import java.util.Collection;

import org.omg.PortableServer.POAManagerPackage.State;

import Philips_hue.api.*;

public class Test 
{
	public static void main(String args[]) 
	{
		final String bridgeIp = "192.168.178.555"; // Fill in the IP address of your Bridge
		final String apiKey = "k55bmvO5SiJGgc7eFzzvuOTbZv83VEepPm-HIMCm"; // Fill in an API key to access your Bridge
		final Hue hue = new Hue(bridgeIp, apiKey);
		final Room room = hue.getRoomByName("Woonkamer").get();
			
			room.getLightByName("Zuil").get().turnOff();

i would appriciate it if you can help me

thanks in advance

**Comment by ZeroOne3010** [comment]
You have your import wrong. The package is not Philips_hue.api.*, it should be `io.github.zeroone3010.yahueapi.*`.

**Comment by MrBlik123** [comment]
ah ok thanks for the help and the library i really respect it that you put in so much work for a library thanks a lot for the help
